flutter:
  assets:
    - assets/pftmap.jpg
    - assets/page_1.jpg
    - assets/page_2.jpg
    - assets/page_3.jpg
    - assets/page_4.jpg
    - assets/page_5.jpg
    - assets/page_6.jpg
    - assets/page_7.jpg
    - assets/page_8.jpg
    - assets/page_9.jpg
    - assets/page_10.jpg
    - assets/page_11.jpg
    - assets/page_12.jpg
    - assets/page_13.jpg
    - assets/page_14.jpg
    - assets/LSUlogo.png 